language: php
sudo: false
cache: bundler

php:
  - 7.3
  - 7.2
  - 7.1
  - 7.0
  - 5.6
  - 5.5
  - 5.4
  - hhvm-3.30

matrix:
  allow_failures:
    - php: hhvm
  fast_finish: true
  include:
    - php: 5.3
      dist: precise


before_script:
  - composer self-update
  - composer install

script:
  - ./vendor/bin/phpunit --coverage-clover=coverage.clover
  - ./vendor/bin/phpcs --standard=PSR2 src/ tests/

after_script:
  - sh -c 'if [ "$TRAVIS_PHP_VERSION" != "hhvm-3.30" ]; then wget https://scrutinizer-ci.com/ocular.phar; fi;'
  - sh -c 'if [ "$TRAVIS_PHP_VERSION" != "hhvm-3.30" ]; then php ocular.phar code-coverage:upload --format=php-clover coverage.clover; fi'
