language: php
sudo: false
cache: bundler

php:
  - 7.0
  - 5.6
  - 5.5
  - 5.4
  - 5.3
  - 7.0
  - hhvm

matrix:
  allow_failures:
    - php: hhvm, 7.0
  fast_finish: true

before_script:
  - composer self-update
  - composer install

script:
  - ./vendor/bin/phpunit --coverage-clover=coverage.clover
  - ./vendor/bin/phpcs --standard=PSR2 src/ tests/

after_script:
  - sh -c 'if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then wget https://scrutinizer-ci.com/ocular.phar; fi;'
  - sh -c 'if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then php ocular.phar code-coverage:upload --format=php-clover coverage.clover; fi'
