site_name: 'SnappyRouter'
pages:
- Home:
  - Home: index.md
  - Getting Started: getting_started.md
- Handlers:
  - Handlers: handlers/index.md
  - Controller Handler: handlers/controller_handler.md
  - Rest Handler: handlers/rest_handler.md
  - Pattern Match Handler: handlers/pattern_handler.md
  - Direct Script Handler: handlers/direct_handler.md
  - JSON RPC Handler: handlers/jsonrpc_handler.md
  - CLI Task Handler: handlers/cli_handler.md
- Plugins:
  - Plugins: plugins/index.md
- Dependency Injection:
  - Dependency Injection: di.md
theme: 'readthedocs'
